### ISSUE TITLE
PostAsJsonAsync<T> extension ignores HttpClient's BaseAddress

### ISSUE THREAD

**Issue by karosas** [SCADAMINDS/swiss-army-knife#26]
### Describe the bug

`PostAsJsonAsync<T>` extension (others too I guess) ignores `HttpClient`'s `BaseAddress`.

### To Reproduce

```
var client = new HttpClient() { BaseAddress = "http://localhost/ }
client.PostAsJsonAsync<object>("/my/relative/path");
```
### Expected behaviour

Extension combines `HttpClient`'s `BaseAddress` with path specified in the method parameters.

**Comment by GeeWee** [comment]
Well spotted.
Do you want to give a PR a shot?

**Comment by karosas** [comment]
> Well spotted.
> Do you want to give a PR a shot?

At some point if nobody else wants to do it, I just put it up as a reminder

**Comment by GeeWee** [comment]
I actually had some time this morning, so I have a PR about to be merged in for it :)

**Comment by GeeWee** [comment]
You should be able to pull [1.4.2](https://www.nuget.org/packages/SCM.SwissArmyKnife/) from nuget now where the fix is.
